 #port config
server:
  port: 8080

 #app config
spring:
  application:
    name: api

 #mysql config
  datasource:
    url: jdbc:mysql://localhost:3306/cours_test
    username: root
    password: root
  jpa:
    hibernate:
      # drop & create a new db everytime it's run if create-drop, with update, it'll just create on update
      ddl-auto: update